site_name: ResourceD Documentation
site_url: http://resourced.io
repo_name: GitHub
repo_url: https://github.com/resourced/resourced.github.io
theme: readthedocs
docs_dir: content-docs
site_dir: docs
extra_css:
    - css/highlightjs-override.css
    - css/readthedocs-override.css

pages:
    - Home: index.md
    - Gallery: gallery.md
    - "User Installation: Day 1": installation-user-day-1.md
    - "User Installation: Day 2": installation-user-day-2.md
    - "User Installation: Day 3": installation-user-day-3.md
    - "Contributor Installation": installation-dev.md
    - "Documentation Installation": installation-docs.md
    - "Usage - Agent: Metrics: Server": usage-agent-metrics-server.md
    - "Usage - Agent: Metrics: Live": usage-agent-metrics-live.md
    - "Usage - Agent: Application: General": usage-agent-application-general.md
    - "Usage - Agent: Application: Go": usage-agent-application-go.md
    - "Usage - Agent: Logs: File": usage-agent-logs-file.md
    - "Usage - Agent: Logs: Live": usage-agent-logs-live.md
    - "Usage - Agent: Logs: Forwarding": usage-agent-logs-forwarding.md
    - "Usage - Master: Hosts": usage-master-hosts.md
    - "Usage - Master: Graphs": usage-master-graphs.md
    - "Usage - Master: Logs": usage-master-logs.md
    - "Usage - Master: Checks": usage-master-checks.md
    - "API Doc - Master: Auth": api-master-authentication.md
    - "API Doc - Master: GET /api/hosts": api-master-hosts-get.md
    - "API Doc - Master: GET /api/metrics/{id:[0-9]+}": api-master-metrics-get.md
    - "API Doc - Master: GET /api/metrics/{id:[0-9]+}/hosts/{host}": api-master-metrics-host-get.md
    - "API Doc - Master: EventSource /api/metrics/streams": api-master-metrics-sse.md
    - "API Doc - Master: EventSource /api/metrics/{id:[0-9]+}/streams": api-master-metrics-sse-by-id.md
    - "API Doc - Master: EventSource /api/metrics/{id:[0-9]+}/hosts/{host}/streams": api-master-metrics-sse-by-id-host.md
    - "API Doc - Master: POST /api/events": api-master-events-post.md
    - "API Doc - Master: DELETE /api/events/{id:[0-9]+}": api-master-events-delete.md
    - "API Doc - Master: POST /api/logs": api-master-logs-post.md
    - "API Doc - Master: GET /api/logs": api-master-logs-get.md
    - "API Doc - Master: POST /api/metadata/{key}": api-master-metadata-post.md
    - "API Doc - Master: DELETE /api/metadata/{key}": api-master-metadata-delete.md
    - "API Doc - Master: GET /api/metadata/{key}": api-master-metadata-get.md
    - "API Doc - Master: GET /api/metadata": api-master-metadata-all.md
