site_name: ResourceD Documentation
site_url: http://resourced.io
repo_name: GitHub
repo_url: https://github.com/resourced/resourced-master
theme: readthedocs
docs_dir: content-docs
site_dir: docs
extra_css:
    - css/readthedocs-override.css

pages:
    - Home: index.md
    - Gallery: gallery.md
    - "API Doc: Auth": api-authentication.md
    - "API Doc: GET /api/hosts": api-hosts-get-all.md
    - "API Doc: GET /api/metrics/{id:[0-9]+}": api-metrics-get-all.md
    - "API Doc: GET /api/metrics/{id:[0-9]+}/15m": api-metrics-15m-get-all.md
