site_name: ResourceD Documentation
site_url: http://resourced.io
repo_name: GitHub
repo_url: https://github.com/resourced/resourced-master
theme: readthedocs
docs_dir: content-docs
site_dir: docs
extra_css:
    - css/readthedocs-override.css

pages:
    - Home: index.md
    - Gallery: gallery.md
    - "API Doc: Auth": api-authentication.md
    - "API Doc: GET /api/hosts": api-hosts-get.md
    - "API Doc: GET /api/metrics/{id:[0-9]+}": api-metrics-get.md
    - "API Doc: GET /api/metrics/{id:[0-9]+}/15m": api-metrics-15m-get.md
    - "API Doc: GET /api/metrics/{id:[0-9]+}/hosts/{host}": api-metrics-host-get.md
    - "API Doc: GET /api/metrics/{id:[0-9]+}/hosts/{host}/15m": api-metrics-host-15m-get.md
    - "API Doc: POST /api/events": api-events-post.md
    - "API Doc: DELETE /api/events/{id:[0-9]+}": api-events-delete.md
    - "API Doc: POST /api/logs": api-logs-post.md
    - "API Doc: GET /api/logs": api-logs-get.md
    - "API Doc: POST /api/metadata/{key}": api-metadata-post.md
    - "API Doc: DELETE /api/metadata/{key}": api-metadata-delete.md
    - "API Doc: GET /api/metadata/{key}": api-metadata-get.md
    - "API Doc: GET /api/metadata": api-metadata-all.md
